branch-defaults:
  development:
    environment: image-filter-api-dev
    group_suffix: null
  master:
    environment: image-filter-api-prod
    group_suffix: null
  dev/include-image-screenshot:
    environment: image-filter-api-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: image-filter-api
  branch: null
  default_ec2_keyname: eb-image-filter-ec2
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
